### ISSUE TITLE
Désactivé la bannière twitch sur mobile

### ISSUE THREAD

**Issue by stupmedia** [stupmedia/website#4]
La baniere twitch sur mobile cache une partie trop grand de la page il faut mieux la desactiver en navigation tablette et mobile.

**Comment by stupmedia** [comment]
Malgré avoir rajouté ca dans le CSS addictionel,  elle veut pas partir sur mobile...  :)

```
@media (max-width: 1020px) {
    .cp-streamweasels {
        display: none !important;
    }
}
```

ALors que en testant dans l'inspecteur ca marche apriori

**Comment by Durss** [comment]
T'as oublié une accolade fermante un peu avant.
```css

**Comment by Durss** [comment]
T'as oublié une accolade fermante un peu avant:
```css
/* Ajuste le conteneur de l'image de fond */
.cs-entry__overlay-bg.cs-overlay-background {
    position: relative; /* Permet le positionnement absolu de la vidéo */
    width: 100%;
    padding-bottom: 37%; /* Ratio 21:9 (100 / (21/9)) */
}

/*BUG BARRE GRISE*/
@media (min-width: 1020px) {
  .cs-entry__header-large .cs-entry__header-wrap {
    padding-top: 0;
  }
}

/*Ajuste la hauteur du Titre*/
.cs-entry__header  .cs-entry__post-meta:not(:first-child) {
      margin-top: 2.5rem;
      margin-bottom: -2rem;
}
@media (min-width: 1020px) {
    .cs-entry__header-standard .cs-entry__header-info:not(:first-child), .cs-entry__header-large .cs-entry__header-info:not(:first-child) {
        margin-top: -9rem;
    }
// <==========ICIIIIIIIIIIIII IL FAUT FERMER SINON TOUTE LA SUITE SERA PETEEEEE
/* Ajuste la vidéo YouTube */
.cs-video-wrapper .cs-video-inner {
     top: 60% !important; 
}

/*Popup twitch désactivé sur mobile (marche po)*/

@media (max-width: 1020px) {
    .cp-streamweasels {
        display: none !important;
    }
}
```
